import { Response } from 'express';

interface LLMRequest {
  prompt?: string;
  messages?: any[];
  model?: string;
  stream?: boolean;
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export const executeLLMRequest = async (
  reqBody: LLMRequest,
  res: Response,
  systemPrompt: string = 'You are a helpful AI legal assistant.'
): Promise<{ tokensUsed: number }> => {
  // Simulate network latency / queue
  await sleep(600);
  
  const textToStream = "This is a secure response generated by the LexForge AI API Gateway. " +
    "The request was authenticated, rate-limited, and logged successfully. " +
    "In a production environment with provider keys (e.g. OpenAI/Anthropic), this content would be replaced with actual model completions. " +
    "Your system prompt was applied securely on the server-side: '" + systemPrompt + "'";

  const isStreaming = reqBody.stream === true;
  
  if (isStreaming) {
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    
    const words = textToStream.split(' ');
    for (let i = 0; i < words.length; i++) {
      // Simulate token generation time
      await sleep(40 + Math.random() * 40);
      
      const chunk = {
        id: `chatcmpl-${Date.now()}`,
        object: 'chat.completion.chunk',
        created: Math.floor(Date.now() / 1000),
        model: reqBody.model || 'lexforge-legal-v1',
        choices: [{
          delta: { content: words[i] + ' ' },
          index: 0,
          finish_reason: null
        }]
      };
      
      res.write(`data: ${JSON.stringify(chunk)}\n\n`);
    }

    const finalChunk = {
      id: `chatcmpl-${Date.now()}`,
      object: 'chat.completion.chunk',
      created: Math.floor(Date.now() / 1000),
      model: reqBody.model || 'lexforge-legal-v1',
      choices: [{ delta: {}, index: 0, finish_reason: 'stop' }]
    };
    res.write(`data: ${JSON.stringify(finalChunk)}\n\n`);
    res.write('data: [DONE]\n\n');
    res.end();
  } else {
    // Non-streaming response
    res.json({
      id: `chatcmpl-${Date.now()}`,
      object: 'chat.completion',
      created: Math.floor(Date.now() / 1000),
      model: reqBody.model || 'lexforge-legal-v1',
      choices: [{
        message: {
          role: 'assistant',
          content: textToStream
        },
        index: 0,
        finish_reason: 'stop'
      }],
      usage: {
        prompt_tokens: 45,
        completion_tokens: textToStream.length / 4,
        total_tokens: 45 + (textToStream.length / 4)
      }
    });
  }

  // Return rough token count for billing
  return { tokensUsed: Math.floor(45 + (textToStream.length / 4)) };
};
